### PR TITLE
Refactor configuration

### PR DESCRIPTION
**Pull request by gabriele-decapoa**
Refers to #2

### CODE REVIEW

**Comment by dvesperini** [comment]
@gabriele-decapoa One test is failed and merging is blocked.

**Comment by gabriele-decapoa** [comment]
@dvesperini I fixed the tests. Let me know if you cannot merge it.

**Review by dvesperini — APPROVED** [review]
It looks Good

**Comment by dvesperini** [comment]
Everything is ok now ;)

2018-08-12 15:40 GMT+02:00 Gabriele de Capoa <notifications@github.com>:

**Pull request merged**
